const express = require('express');
const bcrypt = require('bcryptjs');
const { setTokenCookie, requireAuth, restoreUser } = require('../../utils/auth');
const { User } = require('../../db/models');
const { Spots } = require('../../db/models')
const { check } = require('express-validator');
const { handleValidationErrors } = require('../../utils/validation');
// const spots = require('../../db/models/spots');
const router = express.Router();

// //get all spots
router.get('/', async (req, res) => {
    const spots = await Spots.findAll();
    res.status(200).json({ Spots: spots });
});

router.get('/current', restoreUser, async (req, res) => {
    const { user } = req;
    // console.log('USER------>', user);
    if (!user) {
        return res.status(401).json({
            message: 'Authentication required',
            statusCode: 401
        });
    }

    const spots = await Spots.findAll({
        where: {
            ownerId: user.id
        }
    });
    return res.json({
        Spots: spots
    });
});

router.post('/', requireAuth, async (req, res) => {
    const { address, city, state, country, lat, lng, name, description, price } = req.body;

    const ownerId = req.user.id;
    // console.log (ownerId);
    if(!address || !city || !state || !country || !lat || !lng || !name || !description || !price){
        return res.status(400).json({
            "message": "Bad Request", // (or "Validation error" if generated by Sequelize),
            "errors": {
              "address": "Street address is required",
              "city": "City is required",
              "state": "State is required",
              "country": "Country is required",
              "lat": "Latitude must be within -90 and 90",
              "lng": "Longitude must be within -180 and 180",
              "name": "Name must be less than 50 characters",
              "description": "Description is required",
              "price": "Price per day must be a positive number"
            }
          })
    }


    const createSpot = await Spots.create({
        ownerId, address, city, state, country, lat, lng, name, description, price})

        res.status(201).json(createSpot);
});

   
module.exports = router;